### ISSUE TITLE
Understanding where smart-configuration lives

### ISSUE THREAD

**Issue by colmbrady** [Alvearie/keycloak-extensions-for-fhir#21]
Hi,

Ive got a question regards the README and this line:

"Discover the authentication and token endpoints from the server's [base]/.well-known/smart-configuration endpoint as described at http://www.hl7.org/fhir/smart-app-launch/conformance/index.html#using-well-known."

**Is this end point meant to be hosted inside the FHIR Server? or Keycloak?** 

From reading the description - I thought that the endpoint would be hosted on the docker container here:

http://localhost:8080/auth/realms/test/.well-known/smart-configuration - but this returns a 404. 

Thanks!

**Comment by colmbrady** [comment]
<img width="624" alt="Screen Shot 2021-07-21 at 9 11 29 AM" src="https://user-images.githubusercontent.com/10607960/126396066-c1921f1f-7e44-4ecc-a80f-9e91c694e1e2.png">

I would of thought the endpoint would be available here ^

**Comment by colmbrady** [comment]
On reflection, I presume the intent is that the FHIR server is the source of truth for how to authenticate with it, so its likely that I was initially misunderstanding the purpose.

**Comment by lmsurpre** [comment]
I updated the README to say `from the *FHIR* server's` to make this more clear.
