### ISSUE TITLE
helm client defaultScopes not configured in keycloak as client assigned default scopes

### ISSUE THREAD

**Issue by kmbarton423** [Alvearie/keycloak-extensions-for-fhir#44]
Deployed with alvearie/ibm-fhir-server helm chart.
Configured for keycloak client inferno defaultScopes: ["launch/patient"].
Attempts to get a token with launch/patient scope were flagged as invalid scope.
From keycloak admin, can see that launch/patient was not configured as a assigned default client scope for inferno (see attached).

**Comment by kmbarton423** [comment]
![keycloadAdmin](https://user-images.githubusercontent.com/69682345/155403258-32305fa0-cbb6-40c3-8047-b8b553b3d988.png)
[values-ksmart.yaml.txt](https://github.com/Alvearie/keycloak-extensions-for-fhir/files/8127630/values-ksmart.yaml.txt)
[helmTemplateOutput.txt](https://github.com/Alvearie/keycloak-extensions-for-fhir/files/8127631/helmTemplateOutput.txt)

**Comment by kmbarton423** [comment]
Confirmed no errors surfaced via logDNA for keycloak-config.

Feb 23 14:21:10 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing realm: test
Feb 23 14:21:14 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing client scope: fhirUser
Feb 23 14:21:15 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing protocol mapper: fhirUser Mapper
Feb 23 14:21:15 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing client scope: launch/patient
Feb 23 14:21:15 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing protocol mapper: Patient ID Claim Mapper
Feb 23 14:21:15 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing protocol mapper: Patient ID Token Mapper
Feb 23 14:21:15 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing protocol mapper: Group Membership Mapper
Feb 23 14:21:16 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing client scope: online_access
Feb 23 14:21:16 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing client scope: patient/*.read
Feb 23 14:21:16 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing protocol mapper: Audience Mapper
Feb 23 14:21:16 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing protocol mapper: Group Membership Mapper
Feb 23 14:21:16 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing client scope: patient/AllergyIntolerance.*
Feb 23 14:21:16 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing protocol mapper: Audience Mapper
Feb 23 14:21:16 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing protocol mapper: Group Membership Mapper
Feb 23 14:21:17 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing client scope: patient/Patient.*
Feb 23 14:21:17 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing protocol mapper: Audience Mapper
Feb 23 14:21:17 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing protocol mapper: Group Membership Mapper
Feb 23 14:21:19 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing client: inferno
Feb 23 14:21:20 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing client: infernoBulk
Feb 23 14:21:20 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing authentication flow: SMART App Launch
Feb 23 14:21:20 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config Created flow with id 'b5abfd3f-1259-43c8-b7d4-93e10f5970c6'
Feb 23 14:21:21 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config Created authenticator config with id '04a33cbe-6b58-4fb8-9ab9-1de3b0544efc'
Feb 23 14:21:21 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config Created authenticator config with id '7928caf1-fa2c-4b11-86e8-7049c297d409'
Feb 23 14:21:22 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing group: fhirUser
Feb 23 14:21:22 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing user: fhiruser
Feb 23 14:21:23 kmbtest-ibm-fhir-server-configure-keycloak-pdgws keycloak-config initializing events config

**Comment by lmsurpre** [comment]
I found that the call to `ClientRepresentation.addDefaultClientScope()` gets ignored if that scope string is already in the optionalClientScope list.

I believe whats happening is this:
1. when `security.oauth.smart.launchPatientScopeEnabled` is set to true (the default), this adds `launch/patient` into the default clientOptionalScope list
2. when we enter the block to assign defaultClientScopes, this entry is already on the optional list (due to number 1 above) and so this call is ignored
3. in the block to assign optionalClientScopes, we have logic to replace the existing list with whatever is configured for this client (which removes `launch/patient` from the optional list in this case

I think we can "fix" it by doing the scope removals first, followed by the additions.  In the case of conflicts (e.g. scopes on both lists), the "defaultClientScopes" list will now win because that gets set first.

**Comment by lmsurpre** [comment]
fixed by https://github.com/Alvearie/keycloak-extensions-for-fhir/pull/68
