### ISSUE TITLE
(minor) error building keycloak-config

### ISSUE THREAD

**Issue by XcrigX** [Alvearie/keycloak-extensions-for-fhir#46]
Minor - The readme instructions state to build the keycloak-config image with the command:
_docker build keycloak-config -t alvearie/keycloak-config_

Run from the project root directory, this yields an error: 
```
 => ERROR [build 3/4] COPY keycloak-config ./keycloak-config                                                                                  0.0s
------
 > [build 3/4] COPY keycloak-config ./keycloak-config:
------
failed to compute cache key: "/keycloak-config" not found: not found
```

Running the command suggested in the Dockerfile works:
_docker build . -f keycloak-config/Dockerfile_

**Comment by lmsurpre** [comment]
thanks @XcrigX ...should be fixed now
